apiVersion: v1
kind: Service
metadata:
  name: {{ include "seo-app.name" . }}
  labels: {{- include "seo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "seo-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
