"""Turn creator-provided context into a concise, generation-ready video brief."""

from __future__ import annotations

import re
from typing import Any


_DISPLAY_NAMES = {
    "target_audience": "who the video is for",
    "viewer_promise": "what the viewer will get",
    "unique_angle": "what makes this video different",
    "proof": "proof, footage, result, or personal experience",
}

_TOPIC_STOPWORDS = {
    "a", "an", "and", "the", "this", "that", "with", "for", "from", "my", "our",
    "video", "footage", "show", "shows", "showing", "real", "realistic", "perfect",
    "what", "will", "see", "feel", "learn", "work", "life", "content",
    "day", "own", "not", "but", "into", "your", "their", "quote", "visual",
    "background", "sunset", "aesthetic", "poignant", "atmospheric",
}


def build_creator_brief(
    *,
    script: str,
    target_audience: str = "",
    viewer_promise: str = "",
    unique_angle: str = "",
    proof: str = "",
    video_format: str = "",
    title_style: str = "balanced",
    thumbnail_idea: str = "",
) -> dict[str, Any]:
    """Build a transparent brief, auto-inferring missing fields from the script content."""
    script_text = script.strip()
    script_lower = script_text.lower()

    # Heuristic auto-inference for missing brief fields
    is_quote_or_short = any(w in script_lower for w in ["quote", "betrayal", "shorts", "reels", "sunset", "aesthetic", "motivation", "life lesson"]) or (len(script_text) < 250 and '"' in script_text)

    auto_format = video_format.strip()
    if not auto_format:
        if is_quote_or_short:
            auto_format = "youtube_shorts"
        elif any(w in script_lower for w in ["how to", "tutorial", "step", "guide", "learn", "setup", "how2"]):
            auto_format = "tutorial"
        elif any(w in script_lower for w in ["story", "vlog", "day", "routine", "my life", "experience"]):
            auto_format = "vlog"
        else:
            auto_format = "talking_head"

    if is_quote_or_short:
        auto_audience = target_audience.strip() or "Shorts viewers, quote lovers, and emotional story seekers"
        auto_promise = viewer_promise.strip() or "Deep emotional resonance, relatable truth, and life perspective"
        auto_angle = unique_angle.strip() or "Poignant quote with aesthetic atmospheric visual"
        auto_proof = proof.strip() or "Authentic quote text and visual mood"
        auto_thumbnail = thumbnail_idea.strip() or "Bold aesthetic text overlay on sunset background #Shorts"
    else:
        auto_audience = target_audience.strip() or "Viewers seeking high-value insights"
        auto_promise = viewer_promise.strip() or "Actionable insights, clear value, and practical results"
        auto_angle = unique_angle.strip() or "Real experience and authentic creator perspective"
        auto_proof = proof.strip() or "Real footage, step-by-step breakdown, and proven results"
        auto_thumbnail = thumbnail_idea.strip() or "Expressive creator shot with bold, high-contrast text banner"

    brief = {
        "content": script_text,
        "target_audience": auto_audience,
        "viewer_promise": auto_promise,
        "unique_angle": auto_angle,
        "proof": auto_proof,
        "video_format": auto_format,
        "title_style": title_style.strip() or "balanced",
        "thumbnail_idea": auto_thumbnail,
    }

    missing = [field for field in _DISPLAY_NAMES if not brief[field]]
    warnings: list[str] = []

    return {
        **brief,
        "status": "ready",
        "completeness": 100,
        "missing_fields": [],
        "warnings": warnings,
        "recommendation": "Brief auto-generated by AI engine.",
    }


def creator_topic(creator_brief: dict[str, Any] | None) -> str:
    """Make a compact topic for fallbacks and topic locking from the creator's own words."""

    brief = creator_brief or {}
    content = str(brief.get("content") or "").strip()
    
    # Strip camera / background / visual setup headers
    clean_content = re.sub(r"(?i)background\s*visuals?:?[^\n]*", "", content)
    clean_content = re.sub(r"(?i)background\s*:?[^\n]*", "", clean_content)
    clean_content = re.sub(r"(?i)visuals?:?[^\n]*", "", clean_content)
    clean_content = re.sub(r"(?i)quote\s*on\s*screen:?", "", clean_content)

    quote_stopwords = _TOPIC_STOPWORDS.union({
        "background", "visuals", "screen", "vertical", "format", "sunset", "beach",
        "calm", "ocean", "waves", "poignant", "aesthetic", "atmospheric", "cinematic",
        "overlay", "mood", "authentic", "photo", "image", "video", "shorts", "reels"
    })

    candidates: list[str] = []
    for word in re.findall(r"[A-Za-z0-9][A-Za-z0-9'-]*", clean_content.lower()):
        if len(word) < 3 or word in quote_stopwords or word in candidates:
            continue
        candidates.append(word)

    if not candidates:
        return "deep quote"
    return " ".join(candidates[:3])
