apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.apiseven.com
    chart: apisix
    targetRevision: 2.10.0
    helm:
      releaseName: apisix
      values: |
        gateway:
          type: NodePort
          http:
            nodePort: 30080
        ingress-controller:
          enabled: true
          config:
            apisix:
              serviceNamespace: apisix
        dashboard:
          enabled: true
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: apisix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
